# Generated by Django 3.2.10 on 2022-01-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='date_published',
        ),
        migrations.AddField(
            model_name='summary',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
