# Generated by Django 3.2.10 on 2022-01-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220104_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
