# Generated by Django 3.2.10 on 2022-01-04 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_summary_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
